-- CREATE DATABASE DEV;
-- CREATE TABLE IF NOT EXISTS CONFIG_DICT (
--     L_TYP VARCHAR(300) NOT NULL,
--     M_TYP VARCHAR(300) NOT NULL,
--     S_TYP VARCHAR(300) NOT NULL,
--     K VARCHAR(300) NOT NULL,
--     V VARCHAR(300) NOT NULL,
--     JSON JSONB,
--     RMRK VARCHAR(300)
-- );
-- COMMENT ON TABLE CONFIG_DICT IS '配置字典';
-- COMMENT ON COLUMN CONFIG_DICT.L_TYP IS '配置类型-大类';
-- COMMENT ON COLUMN CONFIG_DICT.M_TYP IS '配置类型-中类';
-- COMMENT ON COLUMN CONFIG_DICT.S_TYP IS '配置类型-小类';
-- COMMENT ON COLUMN CONFIG_DICT.K IS '配置KEY';
-- COMMENT ON COLUMN CONFIG_DICT.V IS '配置VALUE';
-- COMMENT ON COLUMN CONFIG_DICT.RMRK IS '配置描述';
-- CREATE UNIQUE INDEX INDEX_CONFIG_DICT_PK ON CONFIG_DICT (TYP, K, V);

drop table if EXISTS "Values"

